### ISSUE TITLE
add typescript linter

### ISSUE THREAD

**Issue by defactojob** [defactojob/solray#4]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

**Comment by czl1378** [comment]
#3

**Comment by defactojob** [comment]
@czl1378 let's autoformat everything with the linter. ' => ", adding trailing comma and semi-colons, etc.

**Comment by czl1378** [comment]
Ok~

**Comment by defactojob** [comment]
resolved
